# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# hadoint is a Dockerfile linter written in Haskell
# that helps you build best practice Docker images.
# More details at https://github.com/hadolint/hadolint
# testing the pipeline

name: hello-world

on:
  push:
    branches: [ master ]

jobs:
  say-hello:
    name: Print Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"
